### ISSUE TITLE
[pip package]

### ISSUE THREAD

**Issue by penguin1109** [CAPSTONE369/ocr_deploy_v1#5]
[Package Page](https://test.pypi.org/project/fridgeyocr/0.0.1/)

- [x] 우선은 text detection + text recogntion을 하는 패키지로 만들었는데 중요한건 제대로 된 key information extraction이 아직 반영이 안되었기 때문에 위치 / text box의 개수(밀도) 기준으로 `[{'name': '', 'quantity': 1}]`의 형태로 전달 될 것임.
- [ ] 현재 `CUTIE`, `GNN기반` 2개의 모델로 학습을 시키려고 코드를 짜는 중이고, 자연어 기반은 데이터가 pre-training을 위해 많이 필요할것 같아서 사전학습된 `KoCharELECTRA`로 잘 안된다면 앞의 2개시도에 집중할 예정임
- [ ] Text Recognition도 물론 중요하지만 오히려 **제대로 정보를 전달하는 KIE도 못지 않게 중요한 것 같아서** 3월 20일정도까지는 KIE 학습에 집중할 예정

**Comment by sunnyineverywhere** [comment]
@penguin1109  
[{'name': '', 'quantity': 1}] -> 전달 시 quantity 값도 String('')으로 전달 될까요
